name: Jiro
avatar: https://s.gravatar.com/avatar/952ab78c5d7894a988d7cd403bbf9cf4?s=80
description: Practice problems in Machine Learning.
baseurl: "/jiro"
url: ""
footer-links:
  twitter: awnihannun
  github: awni 

# Build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
